config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :welcomes

  resources :news

  resources :interviews

  resources :record_reviews

  resources :live_reviews
  resources :articles
  get    'articles/:slug' => 'articles#show', :as => 'article_show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'welcomes#index'

end

app/controllers/record_reviews_controller.rb
class RecordReviewsController < ApplicationController
  before_action :set_record_review, only: [:show, :edit, :update, :destroy]

  # GET /record_reviews
  # GET /record_reviews.json
  def index
    @record_reviews = RecordReview.all
  end

  # GET /record_reviews/1
  # GET /record_reviews/1.json
  def show
  end

  # GET /record_reviews/new
  def new
    @record_review = RecordReview.new
  end

  # GET /record_reviews/1/edit
  def edit
  end

  # POST /record_reviews
  # POST /record_reviews.json
  def create
    @record_review = RecordReview.new(record_review_params)

    respond_to do |format|
      if @record_review.save
        format.html { redirect_to @record_review, notice: 'Record review was successfully created.' }
        format.json { render :show, status: :created, location: @record_review }
      else
        format.html { render :new }
        format.json { render json: @record_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /record_reviews/1
  # PATCH/PUT /record_reviews/1.json
  def update
    respond_to do |format|
      if @record_review.update(record_review_params)
        format.html { redirect_to @record_review, notice: 'Record review was successfully updated.' }
        format.json { render :show, status: :ok, location: @record_review }
      else
        format.html { render :edit }
        format.json { render json: @record_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /record_reviews/1
  # DELETE /record_reviews/1.json
  def destroy
    @record_review.destroy
    respond_to do |format|
      format.html { redirect_to record_reviews_url, notice: 'Record review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record_review
      @record_review = RecordReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_review_params
      params.require(:record_review).permit(:title, :subtitle, :image_one, :image_two, :content)
    end
end

app/helpers/record_reviews_helper.rb
module RecordReviewsHelper
end

app/views/record_reviews/_form.html.erb
<%= form_for(@record_review) do |f| %>
  <% if @record_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record_review.errors.count, "error") %> prohibited this record_review from being saved:</h2>

      <ul>
      <% @record_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :image_one %><br>
    <%= f.text_field :image_one %>
  </div>
  <div class="field">
    <%= f.label :image_two %><br>
    <%= f.text_field :image_two %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/record_reviews/edit.html.erb
<h1>Editing Record Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @record_review %> |
<%= link_to 'Back', record_reviews_path %>

app/views/record_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Record Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Image one</th>
      <th>Image two</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @record_reviews.each do |record_review| %>
      <tr>
        <td><%= record_review.title %></td>
        <td><%= record_review.subtitle %></td>
        <td><%= record_review.image_one %></td>
        <td><%= record_review.image_two %></td>
        <td><%= record_review.content %></td>
        <td><%= link_to 'Show', record_review %></td>
        <td><%= link_to 'Edit', edit_record_review_path(record_review) %></td>
        <td><%= link_to 'Destroy', record_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record review', new_record_review_path %>

app/views/record_reviews/new.html.erb
<h1>New Record Review</h1>

<%= render 'form' %>

<%= link_to 'Back', record_reviews_path %>

app/views/record_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @record_review.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @record_review.subtitle %>
</p>

<p>
  <strong>Image one:</strong>
  <%= @record_review.image_one %>
</p>

<p>
  <strong>Image two:</strong>
  <%= @record_review.image_two %>
</p>

<p>
  <strong>Content:</strong>
  <%= @record_review.content %>
</p>

<%= link_to 'Edit', edit_record_review_path(@record_review) %> |
<%= link_to 'Back', record_reviews_path %>