config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :welcomes

  resources :news

  resources :interviews

  resources :record_reviews

  resources :live_reviews
  resources :articles
  get    'articles/:slug' => 'articles#show', :as => 'article_show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'welcomes#index'

end

app/controllers/live_reviews_controller.rb
class LiveReviewsController < ApplicationController
  before_action :set_live_review, only: [:show, :edit, :update, :destroy]

  # GET /live_reviews
  # GET /live_reviews.json
  def index
    @live_reviews = LiveReview.all
  end

  # GET /live_reviews/1
  # GET /live_reviews/1.json
  def show
  end

  # GET /live_reviews/new
  def new
    @live_review = LiveReview.new
  end

  # GET /live_reviews/1/edit
  def edit
  end

  # POST /live_reviews
  # POST /live_reviews.json
  def create
    @live_review = LiveReview.new(live_review_params)

    respond_to do |format|
      if @live_review.save
        format.html { redirect_to @live_review, notice: 'Live review was successfully created.' }
        format.json { render :show, status: :created, location: @live_review }
      else
        format.html { render :new }
        format.json { render json: @live_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /live_reviews/1
  # PATCH/PUT /live_reviews/1.json
  def update
    respond_to do |format|
      if @live_review.update(live_review_params)
        format.html { redirect_to @live_review, notice: 'Live review was successfully updated.' }
        format.json { render :show, status: :ok, location: @live_review }
      else
        format.html { render :edit }
        format.json { render json: @live_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /live_reviews/1
  # DELETE /live_reviews/1.json
  def destroy
    @live_review.destroy
    respond_to do |format|
      format.html { redirect_to live_reviews_url, notice: 'Live review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_live_review
      @live_review = LiveReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def live_review_params
      params.require(:live_review).permit(:title, :subtitle, :image_one, :image_two, :content)
    end
end

app/helpers/live_reviews_helper.rb
module LiveReviewsHelper
end

app/views/live_reviews/_form.html.erb
<%= form_for(@live_review) do |f| %>
  <% if @live_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@live_review.errors.count, "error") %> prohibited this live_review from being saved:</h2>

      <ul>
      <% @live_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :image_one %><br>
    <%= f.text_field :image_one %>
  </div>
  <div class="field">
    <%= f.label :image_two %><br>
    <%= f.text_field :image_two %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/live_reviews/edit.html.erb
<h1>Editing Live Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @live_review %> |
<%= link_to 'Back', live_reviews_path %>

app/views/live_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Live Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Image one</th>
      <th>Image two</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @live_reviews.each do |live_review| %>
      <tr>
        <td><%= live_review.title %></td>
        <td><%= live_review.subtitle %></td>
        <td><%= live_review.image_one %></td>
        <td><%= live_review.image_two %></td>
        <td><%= live_review.content %></td>
        <td><%= link_to 'Show', live_review %></td>
        <td><%= link_to 'Edit', edit_live_review_path(live_review) %></td>
        <td><%= link_to 'Destroy', live_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Live review', new_live_review_path %>

app/views/live_reviews/new.html.erb
<h1>New Live Review</h1>

<%= render 'form' %>

<%= link_to 'Back', live_reviews_path %>

app/views/live_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @live_review.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @live_review.subtitle %>
</p>

<p>
  <strong>Image one:</strong>
  <%= @live_review.image_one %>
</p>

<p>
  <strong>Image two:</strong>
  <%= @live_review.image_two %>
</p>

<p>
  <strong>Content:</strong>
  <%= @live_review.content %>
</p>

<%= link_to 'Edit', edit_live_review_path(@live_review) %> |
<%= link_to 'Back', live_reviews_path %>